ARG ALPINE_VERSION=3.23.5

FROM docker.io/library/alpine:${ALPINE_VERSION}

ARG TEMPORAL_CLI_VERSION=1.7.2

COPY binaries/${TEMPORAL_CLI_VERSION}/temporal /.temporal/temporal

# Copy custom secrets loader script
COPY entry-scripts/load-secrets.sh /load-secrets.sh

RUN chmod 777 /.temporal/temporal && \
    chmod 777 /load-secrets.sh && \
    mkdir /temporal_db

ENV PATH=/.temporal:${PATH}

VOLUME /temporal_db

EXPOSE 7233
EXPOSE 8080
EXPOSE 45965

WORKDIR /temporal_db

ENTRYPOINT ["temporal", "server", "start-dev", "--db-filename", "temporal.db", "--port", "7233", "--ui-port", "8080", "--metrics-port", "45965", "--ip", "0.0.0.0"]
